name: ShellCheck

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt update
          sudo apt install -y shellcheck

      - name: Run ShellCheck
        run: |
          find . -name "*.sh" -exec shellcheck -S error {} \;
